export type Route = {
  slug: string;
  from: string;
  to: string;
  fromCode: string;
  toCode: string;
  fromCity: string;
  toCity: string;
  mode: "Sea" | "Air" | "Road";
  days: number;
  rate: number;
  region: "Europe" | "Middle East" | "Africa" | "Americas" | "Asia-Pacific" | "Oceania";
  short: string;
  desc: string;
  freqWeekly: number;
  vesselsServed?: string[];
  carriers?: string[];
  documents: string[];
  notes: string;
};

export const ROUTES: ReadonlyArray<Route> = [
  {
    slug: "mumbai-rotterdam",
    from: "Mumbai (BOM)",
    to: "Rotterdam (RTM)",
    fromCode: "BOM",
    toCode: "RTM",
    fromCity: "Mumbai",
    toCity: "Rotterdam",
    mode: "Sea",
    days: 21,
    rate: 142000,
    region: "Europe",
    short: "Backbone of India–Europe ocean trade",
    desc: "Our most-asked lane. Weekly sailings on three carrier alliances, with ECA-compliant fuel surcharges priced honestly. Cape of Good Hope routing default since the Red Sea reroute.",
    freqWeekly: 4,
    carriers: ["MSC", "Maersk", "CMA CGM", "Hapag-Lloyd"],
    documents: ["Commercial invoice", "Packing list", "Bill of lading", "Certificate of origin", "EUR.1 movement"],
    notes: "Cape routing adds 7-9 days vs Suez baseline. Premium for Suez where carrier risk-premium is paid.",
  },
  {
    slug: "mumbai-dubai",
    from: "Mumbai (BOM)",
    to: "Dubai (DXB)",
    fromCode: "BOM",
    toCode: "DXB",
    fromCity: "Mumbai",
    toCity: "Dubai",
    mode: "Air",
    days: 2,
    rate: 38500,
    region: "Middle East",
    short: "The everyday GCC corridor",
    desc: "Daily wide-body capacity on Emirates and IndiGo CarGo. Two-day tail-to-tail standard, same-day for express. Heavy general cargo and pharma both move on this lane.",
    freqWeekly: 14,
    carriers: ["Emirates SkyCargo", "Etihad Cargo", "IndiGo CarGo"],
    documents: ["Commercial invoice", "Packing list", "Air waybill", "Certificate of origin"],
    notes: "GCC e-Mirsal customs, single-window destination clearance.",
  },
  {
    slug: "chennai-mombasa",
    from: "Chennai (MAA)",
    to: "Mombasa (MBA)",
    fromCode: "MAA",
    toCode: "MBA",
    fromCity: "Chennai",
    toCity: "Mombasa",
    mode: "Sea",
    days: 14,
    rate: 98000,
    region: "Africa",
    short: "East Africa's gateway from South India",
    desc: "Tea, textiles, and pharmaceuticals out; capital goods back. Direct fortnightly services with backhaul rates that surprise on the upside.",
    freqWeekly: 2,
    carriers: ["Pacific International Lines", "MSC", "ONE"],
    documents: ["Commercial invoice", "Packing list", "Bill of lading", "Certificate of origin", "ICUMS pre-clearance"],
    notes: "Mombasa cargo dwell averages 4 days; we expedite via Single Window.",
  },
  {
    slug: "delhi-frankfurt",
    from: "Delhi (DEL)",
    to: "Frankfurt (FRA)",
    fromCode: "DEL",
    toCode: "FRA",
    fromCity: "Delhi",
    toCity: "Frankfurt",
    mode: "Air",
    days: 3,
    rate: 52000,
    region: "Europe",
    short: "Pharma's preferred Europe corridor",
    desc: "Lufthansa Cargo's Frankfurt hub gives you onward European feed within 24 hours. CRT-15 and 2-8°C lanes validated end-to-end. Customs pre-clearance via ATLAS.",
    freqWeekly: 12,
    carriers: ["Lufthansa Cargo", "Air India", "Vistara Cargo"],
    documents: ["Commercial invoice", "Packing list", "Air waybill", "EUR.1 movement", "GMP certificate (pharma)"],
    notes: "ATLAS pre-arrival lodgement supported. EU MDR documentation handled at origin.",
  },
  {
    slug: "mundra-lagos",
    from: "Mundra (IXY)",
    to: "Lagos (LOS)",
    fromCode: "IXY",
    toCode: "LOS",
    fromCity: "Mundra",
    toCity: "Lagos",
    mode: "Sea",
    days: 28,
    rate: 168000,
    region: "Africa",
    short: "Long-haul West Africa",
    desc: "Apapa congestion priced into our quote, not added later. SONCAP and PAAR pre-shipment paperwork handled. Backup discharge via Tin Can Island.",
    freqWeekly: 1,
    carriers: ["Maersk", "MSC"],
    documents: ["Commercial invoice", "Packing list", "Bill of lading", "SONCAP", "Form M / PAAR"],
    notes: "Apapa congestion typically 12-18 days at peak; bonded onward truck to interior.",
  },
  {
    slug: "kolkata-singapore",
    from: "Kolkata (CCU)",
    to: "Singapore (SIN)",
    fromCode: "CCU",
    toCode: "SIN",
    fromCity: "Kolkata",
    toCity: "Singapore",
    mode: "Sea",
    days: 9,
    rate: 78000,
    region: "Asia-Pacific",
    short: "Eastern India's APAC gateway",
    desc: "Short, dependable lane for jute, leather, and engineering goods. ASEAN trade preference handled at origin via SAFTA / RCEP filings where applicable.",
    freqWeekly: 3,
    carriers: ["ONE", "Wan Hai", "Evergreen"],
    documents: ["Commercial invoice", "Packing list", "Bill of lading", "RCEP CO Form (where qualifying)"],
    notes: "Singapore TradeNet permits filed pre-arrival; FTZ delivery in 6 hours.",
  },
  {
    slug: "bangalore-london",
    from: "Bangalore (BLR)",
    to: "London (LHR)",
    fromCode: "BLR",
    toCode: "LHR",
    fromCity: "Bangalore",
    toCity: "London",
    mode: "Air",
    days: 2,
    rate: 64500,
    region: "Europe",
    short: "Tech & apparel's premium UK lane",
    desc: "British Airways and Virgin daily widebody capacity. CDS-ready customs documentation for post-Brexit clearance. AOG capability for component spares.",
    freqWeekly: 14,
    carriers: ["British Airways World Cargo", "Virgin Atlantic Cargo", "Air India"],
    documents: ["Commercial invoice", "Packing list", "Air waybill", "CDS declaration data set"],
    notes: "Heathrow ETSF storage available pre-clearance. CDS migration complete since 2023.",
  },
  {
    slug: "hyderabad-tokyo",
    from: "Hyderabad (HYD)",
    to: "Tokyo (NRT)",
    fromCode: "HYD",
    toCode: "NRT",
    fromCity: "Hyderabad",
    toCity: "Tokyo",
    mode: "Air",
    days: 4,
    rate: 58200,
    region: "Asia-Pacific",
    short: "Pharma corridor to Japan",
    desc: "Cool-chain validated for sub-25°C corridors. JIT inbound to pharmaceutical packagers around Narita. Customs pre-clearance via NACCS supported.",
    freqWeekly: 7,
    carriers: ["ANA Cargo", "JAL Cargo", "Cathay Pacific Cargo"],
    documents: ["Commercial invoice", "Packing list", "Air waybill", "JFDA documentation"],
    notes: "NACCS pre-arrival lodgement standard; bonded warehouse at NRT for sub-12h release.",
  },
  {
    slug: "mumbai-new-york",
    from: "Mumbai (BOM)",
    to: "New York (JFK)",
    fromCode: "BOM",
    toCode: "JFK",
    fromCity: "Mumbai",
    toCity: "New York",
    mode: "Air",
    days: 3,
    rate: 92500,
    region: "Americas",
    short: "Trans-Atlantic premium air",
    desc: "Direct widebody capacity on Air India and United, with ACE pre-arrival processing for FDA-regulated and TSA-screened freight.",
    freqWeekly: 10,
    carriers: ["Air India", "United Cargo", "Lufthansa Cargo via FRA"],
    documents: ["Commercial invoice", "Packing list", "Air waybill", "FDA prior notice", "ACAS data set"],
    notes: "TSA-screened cargo only; CCSF-certified packing at origin available.",
  },
  {
    slug: "mumbai-singapore",
    from: "Mumbai (BOM)",
    to: "Singapore (SIN)",
    fromCode: "BOM",
    toCode: "SIN",
    fromCity: "Mumbai",
    toCity: "Singapore",
    mode: "Sea",
    days: 12,
    rate: 84000,
    region: "Asia-Pacific",
    short: "ASEAN gateway by sea",
    desc: "PSA and Jurong terminal calls. Onward feeder to Indonesia, Vietnam, Philippines from a single transhipment.",
    freqWeekly: 5,
    carriers: ["MSC", "PIL", "ONE"],
    documents: ["Commercial invoice", "Packing list", "Bill of lading", "ASEAN-India FTA Form AI"],
    notes: "PSA terminal release within 6 hours of vessel arrival typical.",
  },
  {
    slug: "delhi-sydney",
    from: "Delhi (DEL)",
    to: "Sydney (SYD)",
    fromCode: "DEL",
    toCode: "SYD",
    fromCity: "Delhi",
    toCity: "Sydney",
    mode: "Air",
    days: 4,
    rate: 71000,
    region: "Oceania",
    short: "India ↔ Australia direct freight",
    desc: "Singapore Airlines and Qantas via SIN. Biosecurity-aware packing and AQIS-compliant documentation handled at origin.",
    freqWeekly: 6,
    carriers: ["Qantas Freight", "Singapore Airlines Cargo", "Cathay Pacific Cargo"],
    documents: ["Commercial invoice", "Packing list", "Air waybill", "AQIS biosecurity declaration", "ICS / ICS2 data"],
    notes: "ICS2 ENS data filed at origin; biosecurity holds reduced via pre-clearance.",
  },
  {
    slug: "chennai-hamburg",
    from: "Chennai (MAA)",
    to: "Hamburg (HAM)",
    fromCode: "MAA",
    toCode: "HAM",
    fromCity: "Chennai",
    toCity: "Hamburg",
    mode: "Sea",
    days: 24,
    rate: 138000,
    region: "Europe",
    short: "South India's North Europe ocean lane",
    desc: "Automotive, leather, and chemicals to North Europe. Post-Brexit Hamburg has become the preferred discharge for onward EU distribution.",
    freqWeekly: 3,
    carriers: ["Maersk", "Hapag-Lloyd", "MSC"],
    documents: ["Commercial invoice", "Packing list", "Bill of lading", "EUR.1 movement", "ATLAS data"],
    notes: "Hamburg dwell typically 3-4 days; bonded onward to Benelux and Nordics.",
  },
  {
    slug: "mumbai-jebel-ali",
    from: "Mumbai (BOM)",
    to: "Jebel Ali (JEA)",
    fromCode: "BOM",
    toCode: "JEA",
    fromCity: "Mumbai",
    toCity: "Jebel Ali",
    mode: "Sea",
    days: 5,
    rate: 42000,
    region: "Middle East",
    short: "GCC's container gateway",
    desc: "DP World's flagship terminal — sub-week ocean transit, free zone bonded options, and onward feed to the wider GCC and East Africa.",
    freqWeekly: 7,
    carriers: ["MSC", "Maersk", "PIL"],
    documents: ["Commercial invoice", "Packing list", "Bill of lading", "GCC e-Mirsal data"],
    notes: "JAFZA bonded options available; onward feeder to Bahrain, Qatar, Kuwait same week.",
  },
  {
    slug: "delhi-toronto",
    from: "Delhi (DEL)",
    to: "Toronto (YYZ)",
    fromCode: "DEL",
    toCode: "YYZ",
    fromCity: "Delhi",
    toCity: "Toronto",
    mode: "Air",
    days: 3,
    rate: 86000,
    region: "Americas",
    short: "Canada's premium air corridor",
    desc: "Air Canada and Lufthansa via FRA. CBSA pre-arrival e-Manifest, Indian-diaspora-heavy cargo lane with strong consumer-goods volume.",
    freqWeekly: 5,
    carriers: ["Air Canada Cargo", "Lufthansa Cargo via FRA"],
    documents: ["Commercial invoice", "Packing list", "Air waybill", "CBSA e-Manifest"],
    notes: "Pre-arrival CADEX filing supported; release average 6 hours post-arrival.",
  },
];

export const getRouteBySlug = (slug: string) => ROUTES.find((r) => r.slug === slug);
export const getRoutesByRegion = (region: Route["region"]) =>
  ROUTES.filter((r) => r.region === region);
export const ROUTE_REGIONS: Route["region"][] = [
  "Europe",
  "Middle East",
  "Africa",
  "Americas",
  "Asia-Pacific",
  "Oceania",
];
